### ISSUE TITLE
Please add permission statement to elisp library

### ISSUE THREAD

**Issue by tarsius** [jingtaozf/literate-elisp#1]
This allows the tools that I use to maintain the Emacsmirror to extract the license. Alternatively you could add a LICENSE file, but since people who use your package will likely use itself as inspiration I would prefer the former. (While I might be wrong about this I have a feeling they would be more likely to not follow the example of adding such a file than they would be of not following the example of putting the permission statement where it is put by convention when writing the library directly in a source file.

Thanks!

**Comment by jingtaozf** [comment]
The permission statement has been added into the elisp file, is it fine now?

**Comment by tarsius** [comment]
Yes, thanks!
