### ISSUE TITLE
get-file-char error when calling literate-elisp-byte-compile

### ISSUE THREAD

**Issue by contrapunctus-1** [jingtaozf/literate-elisp#11]
I'm getting an error when running `literate-elisp-byte-compile-file` on the [latest master of jabber.el](https://tildegit.org/wgreenhouse/emacs-jabber/src/branch/master/jabber.org) - `jabber.org:2290:1:Error: Wrong number of arguments: #<subr get-file-char>, 1`.

I don't get a backtrace for this when I enable `toggle-debug-on-error`, and I have not yet figured out just what is calling `get-file-char` (this function is not directly called by `literate-elisp` or `bytecomp`...).

I have not noticed any issues with calling `literate-elisp-load` on the same file, however.

I'm running `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-02-10, modified by Debian`, and the latest Git master of literate-elisp (commit 6979fc6).

**Comment by jingtaozf** [comment]
Can you turn on debug flag of literate-elisp to locate the issue.
```elisp
(setf literate-elisp-debug-p t)
```
Please delete back trace buffer if it exists too.

**Comment by akater** [comment]
`literate-elisp-byte-compile-file` apparently doesn't work at all, and so far I'm surprised if it ever did.

Namely, whitespace-skipping routine seems to be completely broken.

Prepare `test.org` for byte-compilation as follows:
```org
# -*- encoding: utf-8; mode: org; org-src-preserve-indentation: t; -*-

#+BEGIN_SRC elisp
(defun test-- () (random))
#+END_SRC
```

With `test.org` and `literate-elisp.el` in current directory, in `emacs -Q -L .`, run the following:
```elisp
(add-to-list 'load-path "/usr/share/emacs/site-lisp/org/")
;; or wherever org is
(require 'org)
(load "literate-elisp.el")
(literate-elisp-byte-compile-file "test.org")
```

The error is, `get-file-char` (empty arglist) gets called with non-empty arglist in `literate-elisp-peek`.

Emacs version is 27.2 but I don't see any mentions of `get-file-char` changes in commit messages of Emacs git repository.

**Comment by jingtaozf** [comment]
I have tested it in Emacs 27.2 in Mac OS and can't reproduce it.

**Comment by jingtaozf** [comment]
@akater Please re-open this issue if you still have issue

**Comment by akater** [comment]
Yes I still have the issue.  What's the signature of `get-file-char`, in your Emacs 27.2 on Mac OS?

**Comment by akater** [comment]
Here's the backtrace:
```el
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr get-file-char> 1)
  get-file-char(98)
  funcall(get-file-char 98)
  (progn (funcall in c))
  (if c (progn (funcall in c)))
  (let ((c (funcall in))) (if c (progn (funcall in c))) c)
  (cond ((bufferp in) (save-current-buffer (set-buffer in) (if (not (eobp)) (progn (char-after))))) ((markerp in) (save-current-buffer (set-buffer (marker-buffer in)) (if (< (marker-position in) (point-max)) (progn (char-after in))))) ((functionp in) (let ((c (funcall in))) (if c (progn (funcall in c))) c)))
  literate-elisp-peek(get-file-char)
  (cl-find (literate-elisp-peek in) '(10 32 9))
  (while (cl-find (literate-elisp-peek in) '(10 32 9)) (literate-elisp-next in))
  literate-elisp-ignore-white-space(get-file-char)
  literate-elisp-read-datum(get-file-char)
  (setq form (literate-elisp-read-datum in))
  (while t (setq form (literate-elisp-read-datum in)) (if form (progn (throw '--cl-block-nil-- form))) (if literate-elisp-org-code-blocks-p (progn (throw '--cl-block-nil-- nil))) (if (null (literate-elisp-peek in)) (progn (throw '--cl-block-nil-- nil))))
  (let* ((form nil)) (while t (setq form (literate-elisp-read-datum in)) (if form (progn (throw '--cl-block-nil-- form))) (if literate-elisp-org-code-blocks-p (progn (throw '--cl-block-nil-- nil))) (if (null (literate-elisp-peek in)) (progn (throw '--cl-block-nil-- nil)))) nil)
  (catch '--cl-block-nil-- (let* ((form nil)) (while t (setq form (literate-elisp-read-datum in)) (if form (progn (throw '--cl-block-nil-- form))) (if literate-elisp-org-code-blocks-p (progn (throw '--cl-block-nil-- nil))) (if (null (literate-elisp-peek in)) (progn (throw '--cl-block-nil-- nil)))) nil))
  read(get-file-char)
  (byte-compile-file file load)
  (unwind-protect (byte-compile-file file load) (fset 'read original-read))
  (let ((literate-elisp-org-code-blocks-p nil) (load-file-name buffer-file-name) (original-read (symbol-function 'read))) (fset 'read (symbol-function 'literate-elisp-read-internal)) (unwind-protect (byte-compile-file file load) (fset 'read original-read)))
  literate-elisp-byte-compile-file("test.org")
  (progn (literate-elisp-byte-compile-file "test.org"))
  eval((progn (literate-elisp-byte-compile-file "test.org")) t)
```
