### ISSUE TITLE
Interop with describe-*/Helpful/xref

### ISSUE THREAD

**Issue by contrapunctus-1** [jingtaozf/literate-elisp#7]
I tried using `literate-elisp-load` to load my init.org. Given a function I've defined in init.org -
1. `describe-function` does not print a link to jump to its source in init.org
2. `helpful-function` says that this function is 'without a source file', and like #1 does not print a link to the source.
3. `xref-find-definitions` says `No definitions found for: ...`

Can literate-elisp load Org files while maintaining interoperability with the rest of Emacs? If not, can it be extended to do so?

**Comment by jingtaozf** [comment]
I tried both 1 & 3 in my side and they both works.
Have the org file loaded successfully without an exception?

**Comment by contrapunctus-1** [comment]
I think I may have had some errors. Working perfectly now, with all the three cases I mentioned. Beautiful package, thanks! 😀

**Comment by jingtaozf** [comment]
Glad to know. :-)
